# Generated by Django 5.0.1 on 2024-02-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_pupil_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='full_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='school',
            unique_together={('district', 'title')},
        ),
    ]
