# Generated by Django 5.0.1 on 2024-02-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_pupil_full_name_alter_school_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='percent',
            field=models.FloatField(default=0),
        ),
    ]
