# Generated by Django 5.0.1 on 2024-02-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_test_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='percent',
            field=models.FloatField(blank=True),
        ),
    ]
