# Generated by Django 5.0.1 on 2024-02-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_test_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
