# Generated by Django 5.0.1 on 2024-02-03 21:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_test_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
